### ISSUE TITLE
background changes / bugs color

### ISSUE THREAD

**Issue by JL710** [nextcloud/text#6797]
**Describe the bug**
Sometimes the background gets kinda changed until I reopen the document. The background changes in the color of the nextcloud theme (green in my case).
This happens when I copy text or refocus the window.

This does not happen every time, but I cant figure out when it starts and when it ends.

It started after I upgraded from nc 29 to 30.

**To Reproduce**
1. Go to a markdown document
2. mark some text (via cursor or keys)
3. Press ctrl + c or leftclick -> copy
4. Background is highlighted?

Alternatively:
1. Go to a markdown document
2. move the cursor to a specific position
3. focus another window 
4. click back into the markdown document (does not matter if you focus using mouse or shortcuts)

Alternatively 2.:
1. Go to a markdown document
2. find a heading
3. drag the `#` on the left side 
> This one works on Chome as well!
> This one works on my Windows Notebook as well

**Expected behavior**
I would expect it to have the same background after all and just copy the text or do nothing.

**Screenshots**
Before Copying:
![Image](https://github.com/user-attachments/assets/ac96e888-bf03-41f5-90b5-e6f938be0ae3)

After copying:
![Image](https://github.com/user-attachments/assets/d49aedb3-0825-4cf7-86c3-49a8c92a3a03)

Sometimes I get some kind of border as well:
![Image](https://github.com/user-attachments/assets/c7697a3c-60d0-4cef-980d-27f2159011ad)

**Server details:**
- Nextcloud version: 30.0.2

**Client details:**
 - OS: Debian
 - Browser: Firefox
 - Browser version: 133.0.3 (64-bit)
 - Device: desktop

**Comment by mejo-** [comment]
Thanks for your report @JL710! This issue was fixed recently with https://github.com/nextcloud/text/pull/6729 and the fix will be released with the upcoming Nextcloud server point releases.

**Comment by JL710** [comment]
Ops. Did not find the issue in my research. I am glad that this is fixed.

**Comment by JL710** [comment]
@mejo- Is the new version already out? If not, when can we expect it?

**Comment by JL710** [comment]
I somehow have this issue still in version `4.1.0`. and nextcloud `30.0.10` (at least in the notes app). Is this an issue with the text app or should I open an issue in the notes app?
